# Generated by Django 5.1.1 on 2024-09-09 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 9, 9, 11, 26, 5, 666844, tzinfo=datetime.timezone.utc))),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
