# Generated by Django 5.1.1 on 2024-09-24 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 7, 14, 40, 255933, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterModelTable(
            name='snippet',
            table='snippets',
        ),
    ]
